### ISSUE TITLE
Feature request: clean up YAML frontmatter to fit Hugo requirements

### ISSUE THREAD

**Issue by benbohmer** [devidw/obsidian-to-hugo#1]
Obsidian allows
tags: [tag1, tag2, tag3]

Hugo seems to only accept
tags:
- tag1
- tag2
- tag3

Could we check for this and modify accordingly?

**Comment by devidw** [comment]
@benbohmer thanks creating this issue.

It should be possible to use the array syntax with square brackets inside [TOML frontmatter](https://gohugo.io/content-management/front-matter/#front-matter-formats):

```md
+++
…
tags = ['.vimrc', 'plugins', 'spf13-vim', 'vim']
…
+++

…
```

https://gohugo.io/content-management/front-matter/#example
