### ISSUE TITLE
feature request: publish partial files only with specific tag publish: true

### ISSUE THREAD

**Issue by flyingrx** [devidw/obsidian-to-hugo#2]
some docs may be private. It is dangerous to publish all files ignorant of that some files is with account & password.

**Comment by devidw** [comment]
For this purpose, you can set the `draft: true` frontmatter option in your `.md` files and hugo won't process them.

At least, unless you have not explicitly changed the build command of your site to build drafts as well.

Note that this is an entire hugo specific solution, the converter integration will copy drafts as well as any other source files, there is no special logic implemented here.

**Comment by flyingrx** [comment]
yeah, ```draft: true``` is hugo's parameter，and ```publish: true``` is obsidian's parameter.
My practice that treating obsidian as private zone(also at private repo) and treating hugo as public zone(can put at public repo) may be not good, I have no idea. 
Obsidian supports YAML front matter. My scenario is that I have much notes without front matter.I wish I can publish partial notes to hugo when I add front matter with ```draft: true``` or ```publish: true``` to them. Meanwhile, notes without front matter won't be copied to hugo blog repo. 
I'm not sure my practice is proper.

**Comment by flyingrx** [comment]
I take obsidian plugin ```Templater``` to create front matter. It's like this:

---
title: 前端部署流程优化- 打包篇
date: 2022-08-09
description: 上次修改时间: 2022-08-16 22:46
publish: true
tags: [#esuild,#前端]
---

White list may be better than black list. In my scenario I need to add ```draft: true``` to most notes which is huge amount of work.

**Comment by devidw** [comment]
In this case, you could evaluate the option of having different obsidian vaults for private and public notes, or having different subdirectories for private and public notes inside a single vault.

Then you can run the CLI only with the public path, and you should be fine.

**Comment by flyingrx** [comment]
That's a doable solution, thank you.
