### ISSUE TITLE
Hugo fails to build site if page has a link

### ISSUE THREAD

**Issue by hiway** [devidw/obsidian-to-hugo#5]
Thank you for sharing your code. 

I installed via `pip3` , then uninstalled and installed development version via `make` after cloning the repo. Encountered the same issue with both.

Created two pages in the Obsidian vault:

index.md
```
This is a [[test]]
```

test.md
```
Only a test.
```

After running `python3 -m obsidian_to_hugo ...`, I see these two files created in the Hugo `content` folder:

index.md
```
This is a [test]({{< ref "test" >}})
```

test.md
```
Only a test.
```

When I run `hugo`, I get the following error:

```
hugo server -D --disableFastRender
Start building sites … 
hugo v0.104.3+extended darwin/arm64 BuildDate=unknown
ERROR 2022/10/09 02:14:41 [en] REF_NOT_FOUND: Ref "test": "/---/content/index.md:1:18": page not found
Error: Error building site: logged 1 error(s)
```

I have no idea what I'm doing wrong as I'm new to Obsidian, Hugo and this script. 

I have tried "PaperMod" and "etch" themes, no difference.

Any help is appreciated :)

**Comment by devidw** [comment]
Hey @hiway

In Hugo index files are prefixed with a leading underscore:

* https://gohugo.io/content-management/organization/#index-pages-_indexmd
* https://stackoverflow.com/a/62642790/13765033

When you rename your _obsidian/index.md_ into _obsidian/\_index.md_ your Hugo build should pass without any errors.

**Comment by hiway** [comment]
Thank you! I appreciate you taking the time to help a newbie :)

Closing the issue as it is resolved.
