### ISSUE TITLE
mark support

### ISSUE THREAD

**Issue by anakojm** [devidw/obsidian-to-hugo#7]
Hi, what do you think of adding support for converting markdown `==marks==` so they are displayed correctly in html as :`<mark>marks</mark>`.
I already added support in my fork so I can open a  PR if you want

**Comment by devidw** [comment]
Hey @anakojm 

Thank you raising the issue and offering the PR

I think as long as Hugo's goldmark integration does not have built-in support for this and obsidian has this markdown feature, this would be a great addition to the package

As a built-in processor, this can be extended here: https://github.com/devidw/obsidian-to-hugo/blob/4915c344ba5baea17a284571db0a69c4ac915231/src/obsidian_to_hugo/obsidian_to_hugo.py#L22

You are very welcome to PR

**Comment by devidw** [comment]
Closed with #10
