### ISSUE TITLE
dataviewjs support

### ISSUE THREAD

**Issue by anakojm** [devidw/obsidian-to-hugo#8]
What do you think off adding support for the plugin [https://github.com/blacksmithgu/obsidian-dataview](https://github.com/blacksmithgu/obsidian-dataview)

It would convert
~~~markdown
```dataviewjs
// Some javascript
```
~~~
to
```html
<script>
// Some javascript
</script>
```

I already have the code so I can open a PR if you want

**Comment by devidw** [comment]
Hey @anakojm 

Thank you opening this issue

I would like to keep the project focused solely on pure obsidian without any plugin support

Therefore, I'm going to close this one

However, I've extended the package, so anyone can register custom processors using this package. I think this would be the ideal use case here.

Feel free to check out the README on this topic: https://github.com/devidw/obsidian-to-hugo#processors
